### ISSUE TITLE
Question: GIS centered application

### ISSUE THREAD

**Issue by kevhae** [tomwayson/angular2-esri-loader#14]
Hi Tom, Great work, thank you!

I'm planing on using your angular2 esri loader in my angular2, GIS focused application, where the map (and many features of the esri API) will be used on every page.

If I load a module, for Example the FeatureLayer js in one component, will a second component request the FeatureLayer.js a second time, or are files loaded only once?

Thanks a lot, Kevin

**Comment by tomwayson** [comment]
Thanks @kevhae, glad you think this is useful.

> If I load a module, for Example the FeatureLayer js in one component, will a second component request the FeatureLayer.js a second time, or are files loaded only once?

In short, it will be the same behavior that the Dojo loader ordinarily does, which I believe is to cache async scripts after the initial request. Modules like FeatureLayer will already be included in the CDN script, so they won't even be requested.

That said, I strongly encourage you to try and put all references to esri dependencies into a single module, for example, an Angular service. Then that service can expose methods like `addLayerToMap()` etc and your components can all reference that service.
