### ISSUE TITLE
The naming problem

### ISSUE THREAD

**Issue by tomwayson** [tomwayson/angular2-esri-loader#15]
Thanks to "it's just Angular" we should rename to angular-esri-loader. 

I'm thinking of releasing the changes in #12 as angular-esri-loader v1.0.0 and that will be what is officially compatible w/ angular v4.0+

We'll leave the existing published release of angular2-esri-loader@1.0.0 out there as a library that is compatible angular v2.

As far as this repo goes, beyond changing the name in all the places, the only thing I can think that should be done is to rename the existing [v1.0.0](https://github.com/tomwayson/angular2-esri-loader/releases/tag/v1.0.0) tag to something like "angular2-esri-loader-v.1.0.0" or something. Then we can use the v1.0.0 tag to point to angular-esri-loader's v1.0.0.

Is that too confusing?

Another option is that we can pull a google on people and just start angular-esri-loader at v4.0.0?

Thoughts? Feelings?

**Comment by TheKeithStewart** [comment]
Having the `angular2-esri-loader-v.1.0.0` tag and then going forward with the `v1.0.0` tag sounds pretty good. 

I don't think going straight to 4 is necessary. The major releases of Angular are supposed to be a much more stable now and I don't anticipate there being any breaking changes anytime soon that would affect this library. So, keeping the version numbers of this library in sync with the version of Angular shouldn't be necessary as we should be pretty backwards compatible going forward. 

I'm thinking to rename the `angular2-esri4-components` library to `angular-esri4-components` as well. I'm assuming I still need to keep the 4 in there for esri as it seems that there are significant API changes between major versions there. Anyone disagree with this?
