### ISSUE TITLE
Having 2 package.json files and publishing from dist ain't all its cracked up to be

### ISSUE THREAD

**Issue by tomwayson** [tomwayson/angular2-esri-loader#19]
Maybe this is a note to self more than anything else, but current release process is:
- update version in package.json
- update version in src/package.json
- `git add .`
- `git commit`
- `npm run build`
- `cd dist`
- `npm publish`
- `cd ..`
- `git tag <version>`
- `git push origin master --tags`

Would be good to automate that. Also, the [current scripts](https://github.com/tomwayson/angular-esri-loader/blob/268b586febd02754ef825021987ab933d8b2adcb/package.json#L5-L14) are out of date and do not reflect that process.

**Comment by andygup** [comment]
Awesome! ...whadayathink about migrating that to a wiki doc for permanent, easy access?

**Comment by TheKeithStewart** [comment]
@tomwayson Regarding the automation that you are considering for publishing from the dist folder, are you thinking of putting this in a CI (i.e. Travis) or did you have something else in mind?

**Comment by tomwayson** [comment]
@andygup I'd rather migrate it into a script!

@TheKeithStewart Although I would like to run the non-existent tests in CI, I don't think CI is needed for publishing.

What I have in mind is moving as much of those steps as possible to npm scripts first. Especially removing src/package.json and having dist/package.json be builit from package.json. That would re-enable the use of `npm version` and get rid of many of the above steps:

Something like the steps in:
https://github.com/mgechev/ngresizable/blob/e48ee0da0997b45ee29459ad8951804e1f2682c3/package.json#L12
where they copy package.json to dist and then run this cleanup script: 
https://github.com/mgechev/ngresizable/blob/e48ee0da0997b45ee29459ad8951804e1f2682c3/tools/cleanup.ts

**Comment by tomwayson** [comment]
If we go the route of copying package.json to dist and modifying via script, need to ensure the ouput looks like the current src/package.json. For example, need to handle moving [angular deps from dev to peer](https://github.com/tomwayson/angular-esri-loader/pull/20#pullrequestreview-40548999).

**Comment by tomwayson** [comment]
closing this since we're deprecating this repo (#37).
