### ISSUE TITLE
Question - getting error with angular2-esri-loader with when trying to use js.arcgis.com/3.20/

### ISSUE THREAD

**Issue by mechachi** [tomwayson/angular2-esri-loader#23]
I created a cli Angular4 app, i followed the 'How to use angular2-esri-loader in an angular-cli application' instructions. It works fine when i run it with esri 4.x version but when i try to switch to 3.x i get a 404 Not Found error when retrieving 'http://js.arcgis.com/3.20/esri/views/MapView.js.' I can tell that the file doesn't exist, my question is do i need to make additional changes to get the esri loader to work with the esri 3.x version?

**Comment by jwasilgeo** [comment]
The API at v4 is different in several ways from v3. There isn't any concept of a "MapView" in v3. Please see:

https://developers.arcgis.com/javascript/latest/guide/migrating/index.html#views

and also the quick start code for v3:

https://developers.arcgis.com/javascript/3/

**Comment by mechachi** [comment]
I realized the MapView and other differences as soon as i posted the question. Got it working, thank you!
