### ISSUE TITLE
Misaligned tiles with Angular4

### ISSUE THREAD

**Issue by z3dmax** [tomwayson/angular2-esri-loader#28]
Hi Tom,
first of all I want to say thanks to you for all of your work.

I follow exactly your guide to add esri map to my angular4 project, but here my result:

![angular4esri](https://user-images.githubusercontent.com/11600678/29209861-06c2e8a0-7e91-11e7-84d5-41eaf33b767a.png)

No error in console....so I don't understand why this happening.
Following my specs:

`"@angular/cli": "^1.2.3",
"@angular/compiler-cli": "4.0.2",
"@types/arcgis-js-api": "^3.21.0",
"angular-esri-loader": "^1.1.0",
"esri-loader": "^1.1.0",
"typescript": "~2.0.3"`

I'll try with a clean new angular 4 app and I let you know.

Have you ever found this issue?

**Comment by TheKeithStewart** [comment]
I've seen this when the wrong version of the ArcGIS CSS file was loaded. Please verify that you are loading the CSS file that corresponds with the version of the ArcGIS library you are using.

**Comment by z3dmax** [comment]
You are right! I add `<link rel="stylesheet" href="https://js.arcgis.com/3.21/esri/css/esri.css">` in my index.html and now it works! (but it is a dirt fix!)
I think I miss something because no one "esri.css" was loaded by my app. Maybe I forgot some css loader?
Where I can find those css loader setting in your example? Which module do those type of works?

Thanks
