### ISSUE TITLE
Main entry point should be index.js instead of index.ts

### ISSUE THREAD

**Issue by noahmulfinger** [tomwayson/angular2-esri-loader#3]
In package.json, the `main` entry is set to `index.ts`. This causes an error when I am importing, as the `export` syntax is not recognized.

**Suggested Fix:** Removing the `main` entry will set the default entry point back to `index.js`. This fixes my error, and esri-angular-cli-example still worked correctly in a local run when I included this change. 

I will go ahead and make a PR for this, unless there is some specific reason index.ts needs to be the main entry point. (As a curious side note, I could only see this error when I loaded the package from npm install. When I loaded it locally through npm link, this error did not occur.)

cc @patrickarlt [This branch](https://github.com/ArcGIS/arcgis-for-developers/tree/nm-resolve-jsapi) has the error for reference.

**Comment by tomwayson** [comment]
resolved in #4
