### ISSUE TITLE
 angular2-esri-loader using Angular v2 error spears 

### ISSUE THREAD

**Issue by AlexOliinyk1** [tomwayson/angular2-esri-loader#30]
Hi 

After recommendation from this post  https://github.com/Esri/esri-loader/issues/29 I'm trying to change logic, based angular-esri-loader solution 

But I can't understood why problem appear like this   
![image](https://user-images.githubusercontent.com/10448723/29919731-23756348-8e53-11e7-9dc4-f7158f202ea4.png)

I'm trying multiple times from different solutions but I can't to do it work.

**Comment by tomwayson** [comment]
Thanks @AlexOliinyk1. 

That code looks right to me, as if it's copied directly from [the Angular 2 instructions](https://github.com/tomwayson/angular-esri-loader#in-an-angular-2-application). Are you getting a run time error, build errors, or just this error in your IDE? If there are different error messages, please provide them.

Can you please provide the versions of typescript, tslint, angular, angular2-esri-loader, and esri-loader that you have installed? If this is an angular-cli app, please also provide the angular-cli version.

**Comment by AlexOliinyk1** [comment]
@tomwayson  changed way of implementation, and now it works. I loaded script from appcomponent
![image](https://user-images.githubusercontent.com/10448723/30161152-1a280158-93d8-11e7-9fbe-c06db6bfd05b.png)

And removed link from index.cshtml

Thanks

**Comment by tomwayson** [comment]
great. glad you got it working.
