### ISSUE TITLE
Angular 5 is live

### ISSUE THREAD

**Issue by andygup** [tomwayson/angular2-esri-loader#33]
Information update only. The current version number is taking many folks by surprise. 

Items of note:
* Compile-time performance gains.
* Potentially significant compile bundle size improvements.
* Ionic Latest v3.8 (2017-10-26) only [supports Angular 4.4.4](https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md#380-2017-10-26)

Angular breaking changes of note:
* Requires TypeScript 2.4.x.
* [i18n Changes](https://github.com/angular/angular/blob/master/CHANGELOG.md#i18n-pipes)

https://github.com/angular/angular/blob/master/CHANGELOG.md

**Comment by tomwayson** [comment]
closing this since we're deprecating this repo (#37).

if anyone has issues using esri-loader w/ Angular 5, they should open those at https://github.com/Esri/esri-loader/issues
