### ISSUE TITLE
Unload the loaded JS objects?

### ISSUE THREAD

**Issue by digz6666** [tomwayson/angular2-esri-loader#35]
Is there any way to unload the loaded JS objects?
I'm using arcgis JS api 3.x and 4.x together in my project due to some features haven't ported to 4.x yet.

When I load the 4.x after the 3.x it throws error. So how should I handle this?
I'm using angularjs 5.

I read that the dojo AMD loader has undef method, can I call this method?:
http://dojotoolkit.org/reference-guide/1.10/loader/amd.html#loader-amd

**Comment by tomwayson** [comment]
Closing. See https://github.com/Esri/esri-loader/issues/62
