### ISSUE TITLE
Cordova / File not found

### ISSUE THREAD

**Issue by dorianboulch** [tomwayson/angular2-esri-loader#6]
Hello,

I'm using your package with cordova. In web browser it works properly but when it's in a webview, it loads the arcgis files through script tag in file:// instead of http://

My code is based on your example :
https://github.com/tomwayson/esri-angular-cli-example

**Comment by andygup** [comment]
@dorianboulch Cordova has its own life-cycle requirements. Have you looked at Ionic?

Can you also provide some additional information:

 Console errors? 

Cordova version?

Operating System and Version (Android or iOS)?

**Comment by dorianboulch** [comment]
I can't use Ionic, I started the project few months ago, it wouldn't be easy to migrate to Ionic.

Console output : 
`Angular is running in the development mode. Call enableProdMode() to enable the production mode.
cordova.js:1188 deviceready has not fired after 5 seconds.
cordova.js:1181 Channel not fired: onPluginsReady
cordova.js:1181 Channel not fired: onCordovaReady
vendor.bundle.js:97865 GET file://js.arcgis.com/4.2 net::ERR_FILE_NOT_FOUND
bootstrap @ vendor.bundle.js:97865
(anonymous) @ vendor.bundle.js:93024
ZoneAwarePromise @ vendor.bundle.js:128243
EsriLoaderService.load @ vendor.bundle.js:93018
Esri4MapService.loadMap @ vendor.bundle.js:93135
Esri4MapComponent.loadMap @ vendor.bundle.js:69944
Esri4MapComponent.ngOnInit @ vendor.bundle.js:69931
Wrapper_Esri4MapComponent.ngDoCheck @ wrapper.ngfactory.js:54
View_EsriMapComponent0.detectChangesInternal @ component.ngfactory.js:54
AppView.detectChanges @ vendor.bundle.js:87538
DebugAppView.detectChanges @ vendor.bundle.js:87733
AppView.internalDetectChanges @ vendor.bundle.js:87523
View_BlockInteractiveMapComponent0.detectChangesInternal @ component.ngfactory.js:129
AppView.detectChanges @ vendor.bundle.js:87538
DebugAppView.detectChanges @ vendor.bundle.js:87733
AppView.internalDetectChanges @ vendor.bundle.js:87523
View_BlockInteractiveMapComponent_Host0.detectChangesInternal @ host.ngfactory.js:29
AppView.detectChanges @ vendor.bundle.js:87538
DebugAppView.detectChanges @ vendor.bundle.js:87733
ViewRef_.detectChanges @ vendor.bundle.js:63686
webpackJsonp.451.DynamicPageComponent.generateBlock @ main.bundle.js:5740
(anonymous) @ main.bundle.js:5704
ZoneDelegate.invoke @ vendor.bundle.js:127949
onInvoke @ vendor.bundle.js:33080
ZoneDelegate.invoke @ vendor.bundle.js:127948
Zone.run @ vendor.bundle.js:127820
(anonymous) @ vendor.bundle.js:128227
ZoneDelegate.invokeTask @ vendor.bundle.js:127982
onInvokeTask @ vendor.bundle.js:33071
ZoneDelegate.invokeTask @ vendor.bundle.js:127981
Zone.runTask @ vendor.bundle.js:127858
drainMicroTaskQueue @ vendor.bundle.js:128125
ZoneTask.invoke @ vendor.bundle.js:128056`

Cordova version : 5.1.1
Angular CLI : 1.0.0-beta.26

I tried to build to :
Android 6.0.1 
IOS 9.3.5 / 10.1.1

**Comment by andygup** [comment]
I don't have any experience in running Angular directly on Cordova without Ionic, so my thoughts below are best guesses.

Item 1: Your Cordova version is almost a year old. Any chance you can upgrade? Cordova 6.5 was just released a week ago and there have been a ton of bug fixes and security enhancements since 5.1.1.

Item 2: From the console.log the first item that caught my attention is this one: `deviceready has not fired after 5 seconds. ` Normally you need to wait for the Cordova `deviceready` event to fire before bootstrapping any third party libraries such as Angular or the ArcGIS JavaScript API on a mobile device.

Item 3: I also recommend loading the ArcGIS JavaScript API from a <script> tag in your main .html file. And loading the CSS from a <link> tag. Here's an example: https://github.com/jwasilgeo/ionic-esri-map/blob/master/www/fullscreen.html. 

Let us know if any of these ideas help?

**Comment by andygup** [comment]
@dorianboulch I have been able to repro your issue on an Android 6 device. We're looking further into this and will advise.

**Comment by andygup** [comment]
Repro details:

Android 6.0.1
Ionic 2.2.1

Additional Notes:
* **CLARIFICATION** This works fine with ArcGIS JS API 3.19 when importing ArcGIS JS API via a script tag in index.html and removing the `this.esriLoader.load()` method. But, it does not work with 4.2. 

With respect to 4.2:
* Here is where `require` is loaded: [`esri-loader`](https://github.com/tomwayson/esri-loader/blob/master/index.ts#L41)
* Tried importing ArcGIS JS API via a script tag in index.html and removing the `this.esriLoader.load()` method. This resulted in the ArcGIS JS API loading everything but the map. The map failed with the following errors:

![image](https://cloud.githubusercontent.com/assets/510440/22614082/3873d9c6-ea3b-11e6-9b34-520e331bf223.png)

**Comment by tomwayson** [comment]
Thanks for looking into this @andygup.

I've never developed and hybrid apps w/ codrova, ionic, etc. So I can't offer any insight as to why it's trying to load the tiles using the `file:` protocol.

However, my guess would be that if you removed esri-loader from your app and just used a nested Dojo `require()` statement to load the ArcGIS modules, that you'd see the exact same behavior.

**Comment by tomwayson** [comment]
One thought. This library is using an older version of esri-loader. The only difference being that if you don't supply a URL in the options, [it would default to using a protocol relative URL](https://github.com/tomwayson/esri-loader/blob/v0.1.2/index.ts#L11). 

Are you using protocol relative urls (i.e. no `http:` or `https:`)? If so, please try w/ `https:`.

If not, I don't really expect that addressing number #5 would fix this b/c w/ 3.x you're supplying the URL, and w/ 4.x you're seeing errors even when using a script tag instead of `this.esriLoader.load()`. That said, it couldn't hurt to bump to esri-loader v0.1.3 and try it.

**Comment by andygup** [comment]
@tomwayson We've seen similar behavior before with Cordova WebView where it turns XHR requests into `file:` requests. 

I'm using SSL paths. My hack bypassed the default URL by including a script tag in the html page and then doing this:

```
      return this.esriLoader.loadModules(['esri/map']).then(([Map]) => {
        // create the map at the DOM element in this component
        const map = new Map(this.mapEl.nativeElement, {
          center: [-118, 34.5],
          zoom: 8,
          basemap: "topo"
        });

      });

```

One thing I haven't done is check to see if this isn't some weird Content Security Policy thing.

**Comment by andygup** [comment]
@dorianboulch we're looking into a fix at ArcGIS JS API 4.3. In the meantime, in order for this to work you'll need to stick with ArcGIS JS API 3.19 using the pattern I described above.

**Comment by dorianboulch** [comment]
Is there a way to intercept xhr requests ?
We could do a workaround by replacing protocols just before the request execution... 
What do you think about it ?

**Comment by dorianboulch** [comment]
I made it work but it's awfull... 
I'm overriding `XMLHttpRequest.open` method so I intercept every url that matches with file://*.arcgis.com then I replace by https before sending the request.

Just a little bit of js :
```javascript
(function() {
  var proxied = window.XMLHttpRequest.prototype.open;
  window.XMLHttpRequest.prototype.open = function(method, url, async, user, pass) {
    if(url.match(/file:\/\/[^+]*.arcgis.com\//)){
      arguments[1] = url.replace('file://', 'https://');
    }
    return proxied.apply(this, [].slice.call(arguments));
  };
})();
```
Waiting for an update of ArcGIS Api...

**Comment by jwasilgeo** [comment]
> Is there a way to intercept xhr requests ?

@dorianboulch, yes, the JSAPI provides a utility for this called `setRequestPreCallback`.  This is [documented in JSAPI 3](https://developers.arcgis.com/javascript/3/jsapi/esri.request-amd.html#esrirequest.setrequestprecallback), but does not appear to be currently [documented in JSAPI 4.2](https://developers.arcgis.com/javascript/latest/api-reference/esri-request.html) (but it is available to you).  I think this is the same idea as your own workaround above.

```javascript
esriRequest.setRequestPreCallback(function(ioArgs) {
    // console.log(ioArgs);

    // do your replacement logic here, for example with the "ioArgs.url" property

    return ioArgs;
});
```

> What do you think about it ?

Not sure, but I wanted to at least point out `setRequestPreCallback`.

**Comment by tomwayson** [comment]
Closing as this is not an issue w/ this library and @jwasilgeo's suggestion seems like it should work.
